baseURL = "http://natsukashii.art"
languageCode = "en-gb"
title = "Natsukashii"
theme = "natsukashii-v1"
publishDir = "DEPLOY"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
